name: Basic CI Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  typecheck-lint:
    name: Type Check & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck || echo "Typecheck needs fixing"

      - name: Lint
        run: pnpm lint || echo "Linting needs fixing"

      - name: Build test
        run: pnpm build || echo "Build needs environment variables"
      - name: Check secrets exist
        run: |
          for name in DATABASE_URL DIRECT_URL NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY; do
            if [ -z "${!name}" ]; then
              echo "::error::$name is missing"
              exit 1
            else
              echo "$name is set"
            fi
          done
       
